# Generated by Django 5.0.6 on 2024-06-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processeddata',
            name='people_count',
            field=models.JSONField(),
        ),
    ]
